#include "RacketCollisionSystem.hpp"
#include "components/Components.hpp"
#include "math/Vec3.hpp"
#include "math/physics/collision/BallObjectIntersection.hpp"
#include "debug/Debug.hpp"

SystemExec RacketCollisionSystem::update(GameContext* context)
{
    for (auto ePlayer : context->registry.getEntitiesWith<Player>()) {
        auto [cPlayerRacketHandle, cPlayerRacketSwing] = context->registry.getComponents<CRacketHandle, CRacketSwing>(ePlayer);
        auto eRacket = cPlayerRacketHandle->racketEntity;
        auto [cRacketPhysical, cRacketTransform3D, cRacketBoundingBox3D, cRacketVelocity3D] =
            context->registry.getComponents<CRacketPhysical, CTransform3D, CBoundingBox3D, CVelocity3D>(eRacket);

        if (!cRacketPhysical || !cRacketTransform3D || !cRacketBoundingBox3D || !cRacketVelocity3D)
            continue;

        for (auto eBall : context->registry.getEntitiesWith<CBall, CTransform3D, CVelocity3D>()) {
            auto [cBallBall, cBallTransform3D, cBallVelocity3D] =
                context->registry.getComponents<CBall, CTransform3D, CVelocity3D>(eBall);

            // 1. DISTANCE CHECK (Optimization)
            Vec3 toBall = cBallTransform3D->pos_m - cRacketTransform3D->pos_m;
            float distSq = toBall.lengthSq();
            float combinedRadius = 0.25f; // Approx racket size + ball radius
            if (distSq > combinedRadius * combinedRadius) continue;

            // 2. PLANE DISTANCE
            // Project ball vector onto racket normal to see how far "above/below" the face it is
            float distFromPlane = toBall.dot(cRacketPhysical->normal);

            // If ball is further away than its radius, it's not touching the face
            if (std::abs(distFromPlane) > cBallBall->radius_m) continue;

            // 3. RADIAL CHECK
            // Find the point on the racket plane closest to the ball
            Vec3 pointOnPlane = toBall - (cRacketPhysical->normal * distFromPlane);
            if (pointOnPlane.lengthSq() > 0.0225f) continue; // 0.15m racket radius squared

            // --- 4. RELATIVE VELOCITY ---
            Vec3 relativeVelocity3D = cBallVelocity3D->vel_mps - cRacketVelocity3D->vel_mps;
            float velocityNormal = relativeVelocity3D.dot(cRacketPhysical->normal);

            if (velocityNormal >= 0.f) continue;

            // --- RESOLUTION ---

            // 1. Calculate Relative Velocity
// This includes the racket's speed from the generative arc.
            Vec3 relVel = cBallVelocity3D->vel_mps - cRacketVelocity3D->vel_mps;

            // 2. Decompose into Normal (Bounce) and Tangential (Friction)
            // Note: cRacketPhysical->normal is controlled by J2 in your rotation system
            float vNormalMag = relVel.dot(cRacketPhysical->normal);

            // Guard: Ball must be moving toward the face
            if (vNormalMag >= 0.0f) return { SystemExecResult::EarlyExit, "vNormalMag >= 0" };

            Vec3 vNormal = cRacketPhysical->normal * vNormalMag;
            Vec3 vTang = relVel - vNormal;

            // 3. APPLY BOUNCE (Elasticity)
            // This is the "Wood" reflecting the ball. 
            // We use a coefficient of restitution (e.g., 0.8)
            float restitution = cRacketPhysical->restitution;
            Vec3 bounceImpulse = -vNormal * (1.0f + restitution);

            // 4. APPLY BRUSH (Friction)
            // This is the "Rubber" grabbing the ball. 
            // Friction determines how much of the racket's tangential speed is "given" to the ball.
            float friction = cRacketPhysical->friction;
            Vec3 frictionImpulse = -vTang * friction;

            // 5. UPDATE BALL VELOCITY
            // New Velocity = Old Velocity + (Bounce + Brush)
            // This naturally accounts for the racket's speed AND the face angle.
            cBallVelocity3D->vel_mps += bounceImpulse + frictionImpulse;

            // 6. UPDATE BALL SPIN (Torque)
            // Spin is generated by the friction impulse "rolling" the ball.
            // The cross product ensures spin axis is perpendicular to the friction direction.
            float radius = cBallBall->radius_m;
            Vec3 spinImpulse = cRacketPhysical->normal.cross(frictionImpulse) / radius;
            cBallBall->spin += spinImpulse * 15.0f; // 15.0 is a constant representing grip/inertia

            // 7. POSITION CORRECTION (Anti-tunneling)
            cBallTransform3D->pos_m += cRacketPhysical->normal * (radius - distFromPlane);
        }
    }
    return { SystemExecResult::Ran };
}